### ISSUE TITLE
Wrong target menu option

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/codetest#25]
https://github.com/KA226-COVID/codetest/blob/6674fef1a422f2c64cc3e7ba0d21fcbe5c085fd2/views/dao/menu.php#L45
The correct target must be import-from-repo.php, like in [instructor_home view](https://github.com/KA226-COVID/codetest/blob/6674fef1a422f2c64cc3e7ba0d21fcbe5c085fd2/views/pages/instructor-home.php.twig#L52).

**Comment by frasese** [comment]
Hidden menu option until solved some problems with java repositories
