### ISSUE TITLE
Check solution isn't blank

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/codetest#42]
https://github.com/KA226-COVID/codetest/blob/d682925616d298fa7c8f261e440c4f234d16cd6c/assets/scripts/codetest.js#L606

When we send an empty solution, button is disabled and never return enabled.

A message is showed at the top of the page but it isn't enough visible to the user because it is far from the button.

**Comment by frasese** [comment]
Solved on 0ab49c5b1aa4ff5a2abc371af15cb21a2c023f36
