### ISSUE TITLE
Error resizing statement ckeditor

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/codetest#45]
https://github.com/KA226-COVID/codetest/blob/0ab49c5b1aa4ff5a2abc371af15cb21a2c023f36/views/pages/exercise-creation-textarea.php.twig#L65

I don't know why, but when you try to resize the textarea of statement, that include a ckeditor, a `style="width: 0px"` is add to the
`<div id="cke_exercise[statement]".....`
and the editor almost disappear.

**Comment by frasese** [comment]
Solved on c9bff7a2321273f014587cf157922c39c368617c
