### ISSUE TITLE
exercisesList

### ISSUE THREAD

**Issue by jvprofe** [JuezLTI/codetest#51]
Error preloading exercises: exercisesList - I believe "exercisesList" is actually a variable name. In this case, shouldn't it be delimited by  percent signs (%), as in other similar cases? Or is actually a typo?

https://github.com/JuezLTI/codetest/blob/f47a48ca361bed34513e4ed87613a5a44b22501f/locale/en/codetest.php#L373

**Comment by frasese** [comment]
Solved in 74e5dfe122b407e517f2ccf861ddf4b788dff6b6
