### ISSUE TITLE
Remember last used language 

### ISSUE THREAD

**Issue by albsierra** [JuezLTI/codetest#60]
https://github.com/JuezLTI/codetest/blob/2682058d74aafe7449858a83860deeae97a5e115/views/exercise/studentExercise.php.twig#L60

Could we use a session var to store last used language to send an answer? If a student is answering an activity with 10 exercises of PostgreSQL, he must select PostgreSQL the first time and CodeTest should remember it to the subsequent exercises.

**Comment by RaZaC-WP** [comment]
In my last PR (https://github.com/JuezLTI/codetest/pull/65) I have proposed a solution to this issue.

**Comment by frasese** [comment]
Resolved in a105f78758ef4e27ca5cc7e568ae6fdaa9c4f65f
